// Generated by scripts/build-demo.mjs. Do not edit by hand.
const CACHE = 'carquiz-1cc1ae3d1ba1';
const PRECACHE = [
  "index.html",
  "ase.html",
  "privacy.html",
  "manifest.webmanifest",
  "app.js",
  "pro.js",
  "index.js",
  "questions.js",
  "ase.js",
  "ase-questions.js",
  "style.css",
  "ase.css",
  "ase-bank/A1.js",
  "ase-bank/A2.js",
  "ase-bank/A3.js",
  "ase-bank/A4.js",
  "ase-bank/A5.js",
  "ase-bank/A6.js",
  "ase-bank/A7.js",
  "ase-bank/A8.js",
  "ase-bank/A9.js",
  "ase-bank/G1.js",
  "fonts/OFL-bungee.txt",
  "fonts/OFL-spacegrotesk.txt",
  "fonts/bungee-latin-ext.woff2",
  "fonts/bungee-latin.woff2",
  "fonts/fonts.css",
  "fonts/space-grotesk-latin-ext.woff2",
  "fonts/space-grotesk-latin.woff2",
  "icons/apple-touch-icon.png",
  "icons/favicon-48.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "images/poster-bg.jpg"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('carquiz-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Serve from cache for instant, offline play; refresh the cache in the background.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(caches.open(CACHE).then(async (cache) => {
    const cached = await cache.match(req, { ignoreSearch: true });
    const fresh = fetch(req).then((res) => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => null);
    if (cached) { e.waitUntil(fresh); return cached; }
    const res = await fresh;
    if (res) return res;
    if (req.mode === 'navigate') return (await cache.match('index.html')) || Response.error();
    return Response.error();
  }));
});
